# gh-dash configuration
# https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/viewing-and-triaging-notifications/managing-notifications-from-your-inbox
# https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
prSections:
  - title: Mine
    filters: author:@me
  - title: Review requested
    filters: review-requested:@me
  - title: Involved
    filters: involves:@me
  - title: OPX
    filters: org:samsara-dev author:tylerbrewer2 author:mdb author:Shivamyadav2512 author:bharling author:cirpo author:nina-nee author:rahulv25 author:Baicheng-MiQ
  - title: OPX review requested
    filters: team-review-requested:samsara-dev/opx
  - title: Infra Plat
    filters: org:samsara-dev author:vsirohi-samsara author:trumant author:nandittiku author:jsm author:eliot1019 author:justiny98 author:ianvernon author:rashmijha1 author:EmmettTan author:jahnavi-srinivasan author:dburger4 author:btajuddin
  - title: samsara-dev Open
    filters: is:open org:samsara-dev
  - title: samsara-dev Closed
    filters: is:closed org:samsara-dev
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved/open
    filters: is:open involves:@me
  - title: Involved/closed
    filters: is:closed involves:@me
  - title: mdb/open
    filters: is:open user:mdb
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 40
  issuesLimit: 20
  view: prs
  layout:
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
theme:
  ui:
    table:
      compact: true
keybindings:
  issues: []
  prs: []
repoPaths:
  samsara-dev/*: ~/co/*
  mdb/*: ~/dev/*
pager:
  diff: ""
