# gh-dash configuration
prSections:
- title: Mine
  filters: author:@me
- title: Review requested
  filters: review-requested:@me
- title: Involved
  filters: involves:@me
- title: mdb/open
  filters: user:mdb
- title: Plat Infra
  filters: org:samsara-dev author:mdb author:trumant author:nandittiku author:jsm author:fordc-99 author:zdylag author:Shivamyadav2512 author:tomateos author:eliot1019 author:charleenwang author:xuantang-ss author:justiny98
- title: samsara-dev
  filters: org:samsara-dev
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved/open
  filters: is:open involves:@me
- title: Involved/closed
  filters: is:closed involves:@me
- title: mdb/open
  filters: is:open user:mdb
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths: {}
pager:
  diff: ""
