# gh-dash configuration
# https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/viewing-and-triaging-notifications/managing-notifications-from-your-inbox
# https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
prSections:
- title: Mine
  filters: author:@me
- title: Review requested
  filters: review-requested:@me
- title: Involved
  filters: involves:@me
- title: Infra Plat
  filters: org:samsara-dev author:vsirohi-samsara author:mdb author:trumant author:nandittiku author:jsm author:fordc-99 author:zdylag author:Shivamyadav2512 author:tomateos author:eliot1019 author:charleenwang author:xuantang-ss author:justiny98 author:ianvernon author:abarya author:bharling author:cirpo
- title: OPX
  filters: org:samsara-dev author:mdb author:Shivamyadav2512 author:abarya author:bharling author:cirpo
- title: DevExp
  filters: org:samsara-dev team-review-requested:samsara-dev/developer-experience
- title: samsara-dev Open
  filters: is:open org:samsara-dev
- title: samsara-dev Closed
  filters: is:closed org:samsara-dev
- title: mdb/open
  filters: user:mdb
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved/open
  filters: is:open involves:@me
- title: Involved/closed
  filters: is:closed involves:@me
- title: mdb/open
  filters: is:open user:mdb
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths:
  samsara-dev/*: ~/co/*
  mdb/*: ~/dev/*
pager:
  diff: ""
